schemapatch:
  disabled: false
  requiredFeatureSets:
  - ""
  - "Default"
  - "TechPreviewNoUpgrade"
swaggerdocs:
  disabled: false
  enforceComments: false
  outputFileName: zz_generated.swagger_doc_generated.go
compatibility:
  disabled: false
