apiVersion: apiextensions.k8s.io/v1 # Hack because controller-gen complains if we don't have this
name: "[TechPreviewNoUpgrade] Infrastructure"
crd: 0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
tests:
  onCreate:
  - name: Should be able to create a minimal Infrastructure
    initial: |
      apiVersion: config.openshift.io/v1
      kind: Infrastructure
      spec: {} # No spec is required for a Infrastructure
    expected: |
      apiVersion: config.openshift.io/v1
      kind: Infrastructure
      spec: {}
  onUpdate:
  - name: Status Should contain default fields
    initial: |
      apiVersion: config.openshift.io/v1
      kind: Infrastructure
      spec: {}
      status: {}
    updated: |
      apiVersion: config.openshift.io/v1
      kind: Infrastructure
      spec: {}
      status: {}
    expected: |
      apiVersion: config.openshift.io/v1
      kind: Infrastructure
      spec: {}
      status:
        cpuPartitioning: None
        infrastructureTopology: HighlyAvailable
        controlPlaneTopology: HighlyAvailable
  - name: Status update cpuPartitioning should fail validation check
    initial: |
      apiVersion: config.openshift.io/v1
      kind: Infrastructure
      spec: {}
      status:
        cpuPartitioning: None
    updated: |
      apiVersion: config.openshift.io/v1
      kind: Infrastructure
      spec: {}
      status:
        cpuPartitioning: "Invalid"
    expectedStatusError: 'status.cpuPartitioning: Unsupported value: "Invalid": supported values: "None", "AllNodes"'
